INSERT INTO wombats_db.bulletins (bulletin_id, bulletin_title, bulletin_text, bulletin_date) VALUES
(1, 'Sformowanie eskadry', '<img style="float: left; margin-right: 10px;" src="https://i.imgur.com/okHe5mz.png" width="200">Z dniem 10 czerwca 2020 roku powstała eskadra VMFA-117 "Mighty Wombats". Nasza idea to wysoki poziom realizmu bez niepotrzebnej spiny. Nasz szczegółowy statut jest dostępny <a href=''https://forum.gildia.org/viewtopic.php?f=141&t=3723&p=18231#p18231'' style=''color: cyan;''>na gildia.org</a> oraz w zakładce <a href=''http://vmfa-117.org/onas.php'' style=''color: cyan;'' target=_blank>"o nas"</a>.', '2020-06-12'),
(2, 'Rekrutacja', '<img style="float: left; margin-right: 10px;" src="https://i.imgur.com/2Dcy9HN.jpg" width="200">W związku z rozpoczęciem funkcjonowania naszej eskadry, zachęcamy do zgłaszania się do naszego programu. Docelowo chcemy oferować kadetom kompleksowe szkolenie zahaczające o możliwie wszystkie aspekty samolotu F/A-18C. Oczywiście na tę chwilę, program jest dopiero rozwijany.</br></br>

Chcemy ludzi autentycznie zainteresowanym lataniem Hornetem. Takich co w wolnej chwili lubią sobie strzelić OK 3, a w ramach piątkowego relaksu chcą zrobić z kolegami pętlę w parade fomation. Czyli takich, którym nie zabraknie determinacji i wytrwałości.
</br></br>
Nie jesteśmy tu po to, żeby filtrować "tych najlepszych". Chcemy dać Ci pole i zasoby, żebyś stał się tak dobrym v-pilotem, na jakiego Cię stać. W zamian liczymy na to, że będziemy się dobrze bawić przy wspólnych misjach na <a href=''https://forum.gildia.org/'' target=_blank>gildii.org</a>, serewerach otwartych i w misjach z innymi społecznościami.
</br></br>
Dokładniejsze informacje dotyczące aktualnego statusu rekrutacji znajdziesz w zakładce <a href=''http://vmfa-117.org/kontakt.php''>Kontakt/rekrutacja</a>.', '2020-06-12'),
(3, 'Pierwsze 2 miesiące', '<img style="float: left; margin-right: 10px;" src="https://i.imgur.com/4zUeQ6j.jpg" width="300">No i po pierwszych dwóch miesiącach eskadra ruszyła z kopyta. Zaczęliśmy we dwóch, teraz jest nas sześciu, a 3 z 4 naszych kadetów właśnie kończy ogólnolotniczą część szkolenia.
</br></br>
Mamy za sobą wszystkiego już 43 loty, w tym pierwszą kampanię na Gildia.org - <a href=''https://forum.gildia.org/viewtopic.php?f=59&t=3665'' target=_blank>Operation Clothing napisaną przez Avantara</a>. W jej ramach wykonaliśmy cztery loty bojowe, w sumie 10 sorties - w tym raz obsadziliśmy 4-ship. Sukcesem zakończyliśmy 2x CAP, 1x Escort, 1x Anti Ship. Ponadto dwukrotnie prowadziliśmy koordynację operacji ze stanowiska AWACS. Zestrzeliliśmy 4 nieprzyjacielskie samoloty, w tym 2ndLT Kisi trzy zestrzelenia - w swoich pierwszych misjach bojowych, nie ma lipy. Zniszczyliśmy trzy elementy Przeciwlotniczych Zestawów Pocisków Rakietowych i uszkodziliśmy dwa wrogie okręty.</br></br>Myślę, że są powody do zadowolenia, chociaż Warfighter lekko od czerwonych oberwał;)', '2020-08-17'),
(4, '1. Loty Testowe', '<img style="float: left; margin-right: 10px;" src="https://i.imgur.com/4AMy6xp.png?2" width="300">Dwóch pierwszych kadetów zaliczyło swoje loty testowe z podstawowych umiejętności lotniczych i przechodzą do szkoleń bojowych.
<br>
<br>
22.08 i 28.08 odpowiednio Kisi i aliant pokazali zdobyte podczas pierwszej części szkolenia umiejętności. Mimo, że nie oddali w tym czasie ani jednego strzału, zgodnie twierdzili, że była to kupa zabawy. Teraz pora "coś wybuchnąć".', '2020-08-28'),
(5, 'Pierwszy strzał na poligonie', '<img style="float: left; margin-right: 10px;" src="https://i.imgur.com/SmkWbCr.png" width="300">Kadet Kisi w ramach szkolenia z obrony przed zagrożeniami z ziemi w dn. 09.09.2020 dokonał historycznego pierwszego strzału na naszym poligonie, odpalając AGM-88 HARM w trybie Self-Protect w kierunku atrapy SA-3 Goa (Newa).
<br><br> Oczywiście skutecznie :)', '2020-09-10'),
(6, 'Koniec okresu próbnego', '<img style="float: left; margin-right: 10px;" src="https://i.imgur.com/LoiTfwb.png" width="300">Dzisiaj zakończył się okres próbny funkcjonowania VMFA-117 w ramach <a href=''https://forum.gildia.org/'' target=_blank>gildii.org</a>. Tym samym Wombaty stały się pełnoprawną częścią spisu eskadr społeczności.
<br>
<br>
"Wszyło nieźle" - podsumował Wikary, dowódca eskadry.
<br>
<br>
"Od razu wiedziałam, że im się uda. Porządne chłopaki. Mało plują i pety dają normalnie, do kiepownicy. Nie jak te pajace z erfors." - skwitowała słynna Pani Frania, ekspertka od spraw czystości kantyny oficerskiej MCAS Miramar, której długa i chwalebna służba prowadziła przez wszystkie rodzaje sił zbrojnych.', '2020-09-10'),
(7, 'Ćwiczenia z marynarką', '12 Września braliśmy udział we wspólnych ćwiczeniach operacji na lotniskowcu w warunkach CASE I, organizowanych przez VFA-313 z USS Theodore Roosevelt (tfu). Niestety dowódca okrętu matki Admirał John McGyldiansky nie zgodził się na tradycyjnego grilla na pokładzie po owocnym dniu lotnym. Po ciężkich walkach udało się przejąć w stan okupacji platformę LSO gdzie dalej pokazywaliśmy wyższość Marines nad Navy, z daleka od czujnego wąsa Admirała', '2020-09-12'),
(8, 'Black Sea vol 6 "Navy Rage"', '<img style="float: left; margin-right: 10px;" width="300" src="https://i.imgur.com/mkzgFQx.gif">15 września 2-ship ze 117 razem z flightem VFA-418 wypełniał TARCAP w osłonie uderzenia na Sukhumi prowadzonego przez VFA 203.
<br>
Misja zakończyła się sukcesem ale akcja nas ominęła. Skończyło się na treningu formacji i oglądaniu widoków, a także lądowaniu na lotniskowcu, bez TACAN i z wiatrem.<br>', '2020-09-17'),
(9, 'DarkMnich po locie testowym', 'Dwugodzinny lot testowy DarkMnicha w asyście Kisiego zakończył się owocnie. Wszystkie zaplanowane działania zostały wykonane, a wnioski zostały wyciągnięte. <br><br>Kolejny kadet rusza dołącza do szkolenia bojowego.', '2020-09-20'),
(10, 'Gildiański CUP #3', 'Wraz z zakończeniem fazy grupowej Gildiańskiego, zakończyły się też występy członków ''117. Zarówno Kisi jak i Wikary skończyli na trzecich miejscach swoich grup z odpowiednio 1/3 i 2/4 wygranymi walkami. Choć wstydzić się nie ma czego, jak na eskadrę, która zaczęła trening BFM tydzień po rozpoczęciu turnieju, to jednak faktem jest, że długa droga przed nami.<br><br>
Na pocieszenie i otarcie łez ekipa turniejowa zrobiła trening TAC z lądowaniem przy silnym bocznym wietrze.', '2020-10-03'),
(11, 'A Drop of Hope IV', '<img style="float: left; margin-right: 10px;" src="https://i.imgur.com/jutxKhT.png" width="300">Całkiem udana misja Hancera na gildii. Wystawiliśmy 3-ship na BARCAP w osłonie Kutaisi. Misja się udała i wróg się nie przebił, a nawet próbował.
<br><br>
Strącono w sumie 5 wrogów, jednak nie bez strat. Gdy wróg zaatakował z dwóch stron, flight się musiał podzielić i w zamieszaniu Jettax znalazł się bez wsparcia w mergu z 29''. MiG wyszedł na dobrą pozycję do strzału R-73 zanim udało się go zestrzelić. Niemniej zadanie wykonane. Semper Wombat!', '2020-10-09'),
(12, 'Nowy członek eskadry', '<img style="float: left; margin-right: 10px;" src="https://i.imgur.com/DJtcU77.jpg" width="300">Z dniem 10.10.2020 do eskadry w charakterze kadeta przyjęty zostaje Bonqu.<br><br>
Serdecznie witamy! Jesteśmy pewni, że doświadczenie będzie pozytywne.', '2020-10-11'),
(13, 'Pierwszy Field Carrier Landing Practice', 'Prawie pełna eskadra (bo minus kolega studenciak) odbyła 21.10.2020 pierwsze planowe szkolenie w operacjach lotniskowcowych. Skupiało się ono na komunikacji, operowaniu w <i>marshall stacku</i>, poprawnym wykonywaniu <i>patternu</i> i wyjściu na <i>groove</i>.<br><br>
Końcówka była lekko szemrana, przez awarię przenośnego IFLOLS (spowodowaną przez sabotażystów z ED gdzieś w marcu), ale dawała wyobrażenie o tym, co chłopaków czeka na łodzi.<br><br>
FOTO: 2nd Lt Jettax w pożyczonej od 232 maszynie, na tle reszty eksadry w treningowych Hornetach VMFAT-101.<br><br>
<a href="https://imgur.com/a/bRnfrgK" styletarget="_blank"><img src="https://i.imgur.com/HcGZvjo.png" style="float: none; margin-left: 200px;" width="300"></img></a>', '2020-10-22'),
(14, 'Defilada z okazji Święta Niepodległości', 'Drobny akcent eskadrowy pojawił się na imprezie z okazji Dnia Niepodległości zorganizowanej przez niezrównaną ekipę <a href="https://www.facebook.com/wbc.iskry/" target="_blank">Wirtualnych Biało-Czerwonych Iskier</a>, we współpracy ze społecznością <a href="https://gildia.org" target="_blank">Gildia.org</a>.<br><br>W <a href="https://youtu.be/PJLVIkJ3PEE?t=1393" target="_blank">defiladzie</a> łączoną formację LIM-2 i MiG-19 poprowadził w CO VMFA-117 Wikary, po czym wystąpił w roli komentatora <a href="https://youtu.be/PJLVIkJ3PEE?t=4112" target="_blank">pokazu WBCI</a>, który razem z indywidualnymi pokazami na <a href="https://youtu.be/PJLVIkJ3PEE?t=2208" target="_blank">Limie-1</a> i <a href="https://youtu.be/PJLVIkJ3PEE?t=2831" target="_blank">MiGu-29</a> był absolutnie fantastycznym, niezapomnianym wydarzeniem, które koniecznie trzeba powtórzyć!', '2020-11-12'),
(15, 'Nowy pilot i klimatyczna misja na morzu Lewantyńskim', 'Rozkazem Departamentu Marynarki z dn. 26.11.2020 eskadra została wzmocniona transferem. Dołącza LT ZipLip, doświadczony pilot US Navy. Witamy serdecznie i liczymy, że kolega szybko pozbędzie się złych nawyków z marynarki i powróci do pełni zdrowia! Na nową drogę życia szybko przypominamy, że w prawdziwym wojsku na jego rangę mówi się "Kapitan". 
<br><br>
Tymczasem w ostatniej misji Gildyjnej wzięła udział jedna sekcja ze 117, co skończyło się zrobieniem kilku fajnych zdjęć.
<br><br>
<a href="https://imgur.com/a/73hzWhH" styletarget="_blank"><img src="https://i.imgur.com/e0lM5vF.png" style="float: none; margin-left: 200px;" width="300"></img></a>', '2020-12-02'),
(16, 'Anchors Aweigh', 'Pierwszy rejs rozpoczęty. Kadeci (-1 z przyczyn technicznych) i kadra zameldowali się wczoraj na pokładzie CVN-73 i rozpoczynają morską część szkolenia.
<br><br>
Jescze kilka ćwiczeń w rejonie Morza Czarnego, a potem kurs na cieśninę Hormuz!
<br><br>
<a href="https://imgur.com/a/GlqqyoL" styletarget="_blank"><img src="https://i.imgur.com/b7E2hyz.jpg" style="float: none; margin-left: 200px;" width="300"></img></a>', '2020-12-06'),
(17, 'Wesołych Świąt!', 'Jeśli zabłądziłeś tu w okolicach Bożego Narodzenia, cała ekipa Wombatów życzy Ci Wesołych Świąt i szczęśliwego Nowego Roku!<br><br>Przypominamy, że godzina policyjna to dobra wymówka do polatania w Sylwestra, a najlepsze fajerwerki przychodzą zaopatrzone w świątecznie pomalowany zestaw GBU!<br><br><br><br>
<a href="https://imgur.com/YCbZkkj"><img src="https://i.imgur.com/YCbZkkj.gif" title="source: imgur.com" style="float: none; padding: 10px; margin-left: 200px;" width="300"></a>', '2020-12-24'),
(18, 'Trzeba mieć hobby', 'Kolega Jettax intensywnie rozwija swoje umiejętności montażu klipów wideo. Ewidentnie idzie to w dobrą stronę.
<br><br>
<iframe width="560" height="315" src="https://www.youtube.com/embed/vBE8ohU0bMs" frameborder="100" allow="accelerometer; autoplay; clipboard-write; margin-left: 200px; encrypted-media; gyroscope; picture-in-picture" allowfullscreen; style="margin-left: 100px"></iframe>', '2021-01-14'),
(19, 'Nowy Kadet', 'Eskadra wita nowego członka. 2LT Jawor dołączył oficjalnie pod koniec stycznia i zdołał wykonać sześć lotów, zanim administracja połapała się, że nie zgadza się liczba wydawanych posiłków w kantynie.<br><br>Witamy i życzymy owocnej pracy z naszymi przyjaznymi instruktorami!', '2021-02-04'),
(20, 'Działo się', 'Za nami bardzo intensywny okres. Po pierwsze pilot Kisi przeszedł swoją kwalifikację bojową i może już stresować się faktem, że nie tylko reprezentuje eskadrę, ale również wystawia wizytówkę systemowi szkoleniowemu.<br><br>
Po drugie lot kwalifikacyjny 1LT Kisiego inauguruje współpracę między 117'' i <a href="https://www.facebook.com/WingedHussars/" target="_blank">73rd Winged Hussars</a>. Misja, stworzona przez Cpt. Poko poszła świetnie, choć nerwy były i stracono jedną maszynę (0 pilotów). Wideoklip z lotu nagrany i zmontowany przez 2LT Jettaxa znaleźć można poniżej.<br><br>
Po trzecie, do eskadry przyjęto aż dwóch nowych pilotów. 2LT Michajlos i 2LT RagingSnake rozpoczeli swoje szkolenie z odnotowanym przez instruktora entuzjazmem. Tradycyjnie życzymy jak najwięcej cierpliwości i wytrwałości. Jak w każdej rządowej posadzie, tak i tu chodzi głównie o to, żeby dotrwać do końca. Ostatni nabytek kadetów, wyczerpuje też zasoby instruktorskie eskadry.<br><br>No i w końcu z dniem 17.02.2021 ustanawia się rozkazem doroczne święto eskadry na <a href="https://www.facebook.com/WombatDay" target="_blank">dzień 22 października</a>. Najwyższy czas!<br><br>
<iframe width="560" height="315" src="https://www.youtube.com/embed/GbfqCCkpSLk" frameborder="100" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen; style="margin-left: 100px"></iframe>', '2021-02-17'),
(21, 'Stivi''s HOT BALL(S) 2021', 'Bardzo udana <a href="https://forum.gildia.org/gildia/event?mid=1292" target="_blank">56(!) osobowa misja na Gildia.org</a>. Być może to początek nowej, świeckiej tradycji gildyjnego ''święta eskadr''.<br><br>

Stivi złożył misję na 19 kluczy, choć jak to w grach online, nie wszystkie znalazły pełną obsadę. Trzy osobne rejony uderzeń na całej północnej granicy Gruzji, pełna obstawa myśliwska, dwie fale graczy i sporo ciekawych wrogów. Co ciekawe, wszystko to przy bardzo dobrej wydajności.<br><br>

Nie ma już najmniejszych wątpliwości, że Gildia jest zdolna zorganizować wydarzenia z rozmachem porównywalnym z najlepszymi zagranicznymi grupami DCS.

', '2021-03-03'),
(22, 'Drugi kadet kończy szkolenie', 'Kolejny miesiąc za nami, kolejny kadet wypromowany. Montowanie materiału wideo było trochę większym wyzwaniem niż ostatnio, ze względu na problemy z jakością źródła i tzw. ''życie''. Ostatecznie <a href="https://www.youtube.com/watch?v=7QrFZfF7KBo" target="_blank">film z misji kwalifikacyjnej</a> 2nd... sry... 1LT alianta został wczoraj ukończony przez nasz jednoosobowy dział PR''u (pozdrawiamy 2nd Lt Jettax''a) i zakwalifikowany do publikacji przez biuro prasowe grupy bojowej. Gratulujemy i życzymy dalszych sukcesów, tak na polu boju jak i w nowej roli szkoleniowej!<br><br>
Rozegraliśmy także kolejną misję z 73rd Winged Hussars, którzy ostatnio uruchomili <a href="https://www.vs73.pl/ " target="_blank">swoją własną stronę eskadrową</a>. Tym razem w misji naszej produkcji udział wzięli piloci z VFA-313, VFS-333, VFA-418 oraz po stronie czerwonej także EC 1/15 ORLY. Choć nie wszystko poszło zgodnie z planem, to jednak mamy kolejny <i>milestone</i> zaliczony.', '2021-03-07'),
(23, 'Winter Offensive 05', 'Kolejna rozbudowana misja na gildia.org. Tym razem Bartek(N) zaproponował złożone wielostronne uderzenie, w którym na 37 maszyn 15 należało do lotnictwa morskiego, w tym klucz czterech Wombatów. Wymusiło to przydzielenie osobnego kontrolera do nadzorowania operacji startu i powrotu. Widać, że poziom prezentowany przez wszystkie eskadry naprawdę rośnie, bo już drugi raz w tym tygodniu mogliśmy brać udział w solidnie wyglądających operacjach CASE III, a w skutek kapryśnego zachowania DCS, także w pięknej (acz frustrującej) nocnej kolejce do tankowca.<br><br>
Oczywiście nie obyło się bez ciekawych zdarzeń, nieuniknionych przy takiej skali przedsięwzięcia. Niektóre systemy zawiodły, niektóre tankowce się nie odzywały, niektórzy piloci o włos uniknęli kolizji. Wszystko to złożyło się na bardzo udany wieczór, którego mocnym akcentem był występ klucza prowadzonego przez Cpt. Poko. Nasza ekipa dostała przydział osłony operacji od płn.-zach., gdzie starła się z czterema przechwytującymi MiG-25 (przenoszącymi R-40) i dwoma MiG-29, strącając 5 wrogich maszyn bez strat własnych. Pretty f*cking ninja, cytując klasyka.<br><br>', '2021-03-19'),
(24, 'Szósty ''pełny'' pilot w eskadrze', 'Po ukończeniu pełnego, trwającego pół roku szkolenia, 1LT Bonqu pokazał, że jest w stanie opanować systemy, techniki i procedury, których znajomość jest oczekiwana od pełnowymiarowego pilota Marines. Tym samym dziś, z tradycyjnym opóźnieniem charakterystycznym dla wszelkiej maści administracji, otrzymaliśmy z departamentu potwierdzenie awansu i uprawnienie do samodzielnych lotów.<br><br>
Serdecznie gratulujemy i mamy nadzieję, że kolega dalej będzie przykładem pilności i roztropności, nawet po dzisiejszej popijawie.<br><br>
Tym razem dział PR eskadry, z przyczyn absolutnie niezależnych, nie był w stanie zebrać materiału wideo. Odzyskaliśmy natomiast jeden, ostatni kadr z drona sekcji technicznej okrętu, który z jakiegoś powodu znalazł się dokładnie na drodze startu maszyny 507. Trwa dochodzenie mające stwierdzić, czy miało to jakiś związek z awarią, jakiej doznała maszyna na początku tej misji.', '2021-04-20'),
(25, 'Nowy kadet, nowy pilot', 'W zeszłym tygodniu 1LT DarkMnich odbył ostatnie zaległe loty i zakończył szkolenie podstawowe. Tym samym eskadra oficjalnie urosła do 7 pełnych pilotów. Gratulujemy i liczymy na kolejne sukcesy!
<br><br>
Jednocześnie, 2LT Dazzel vel LukeN, po odbyciu trzech lotów kwalifikacyjnych otrzymał pozytywną weryfikację i skierowanie na szkolenie jako Wombat-514.
<br><br>
Całą ekipa z zainteresowaniem będzie śledzić jego postępy!', '2021-05-08'),
(26, 'Zmiany, ciągle zmiany...', 'Po pozytywnej ocenie w każdym z trzech lotów próbnych na stan eskadry w charakterze kadeta został przyjęty 2LT Dom. Na razie Wombat 515 tempo szkolenia ma zawrotne.
<br><br>
Jednocześnie życie dogoniło dwóch innych kadetów, którzy z przyczyn niezależnych nie mają czasu na loty. Tak to 2LT Michajlos i 2LT RagingSnake idą na urlop do czasu wyklarowania sytuacji, czego im serdecznie życzymy.
<br><br>
Poza tymi mieszanymi informacjami chodzą słuchy, że niedługo rozpocznie się nowy projekt kierownictwa. Dowództwo eskadry nie wątpi, że wszyscy nie mogą się doczekać i dadzą temu należyte dowody, gdy już zostanie ogłoszone o co chodzi.', '2021-06-01'),
(27, '12 months of wombating!', 'I tak oto niespodziewanie minął okrągły rok od chwili sformowania eskadry w ramach gildia.org. W tym czasie wylataliśmy 1500 osobogodzin, wykonanliśmy okrągłe 240 lotów wszystkich kategorii i zapełniliśmy równo 230 slotów w misjach HRP. Nie było łatwo, ale na pewno było warto.
<br><br>
Zobaczymy co przyniesie rok kolejny!
<br><br>
<iframe width="560" height="315" src="https://www.youtube.com/embed/IlnMpcfjvJ4" frameborder="100" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen; style="margin-left: 100px"></iframe>', '2021-06-12'),
(28, 'Wakacyjne klimaty', 'Jak co lato zaczyna się czas urlopowania i aktywność lotnicza spada. Nie pomaga wysoka temperatura w wirtualnych kokpitach. Niemniej to właśnie teraz, po bardzo długim (3h+) locie, szkolenie ogólne z wynikiem pozytywnym zakończył 2LT Dom. Podobnie, po intensywnym tygodniu pracy, nowy kandydat na kadeta 2LT soczkien ma przed sobą ostatni lot próbny, zanim podjęta zostanie decyzja o jego przyjęciu na stan eskadry.
<br><br>
W ostatnim miesiącu eskadra wystawiła silną reprezentację na pięciu misjach oficjalnych gildii, w tym bardzo solidnej akcji nad Aleppo, autorstwa Alienzo, gdzie wystąpiliśmy w jednym kluczu z US Navy (313th). Operując w wąskim korytarzu, w warunkach sporego pokrycia chmurami, piloci dokonali bombardowania wyznaczonych pozycji wroga, a następnie podjęli próbę rozpoznania sił ''sojuszniczych'' rosyjskich jednostek pancernych. To drugie zadanie okazało się bardzo trudne i sukces był częściowy. Konieczność łączenia uważnej nawigacji, czujnego wyszukiwania ognia z ziemi i wypatrywania jednostek naziemnych późnym, pochmurnym wieczorem były bardzo ciekawym doświadczeniem.
<br><br>
Co warte odnotowania, dwa boltery i no grade dowódcy podczas nocnego powrotu na pokład dobitnie dowodzą wadliwego działania pomocy nawigacyjnych na CVN-72, na którym gościliśmy w tej misji. Zastrzeżenia zostały zgłoszone do Admirała właściwą drogą służbową.
<br><br>
No i kiedyś ten moment nastąpić musiał. Pierwsze dwa Wombaty przechodzą do rezerwy ze względu na brak czasu na loty. Serdecznie dziękujemy 2LT Michajlosowi i 2LT RagingSnake''owi za wspólne loty!', '2021-07-09'),
(29, 'Wakacyjne przemeblowania', 'Po pół roku pełnienia de facto funkcji zastępcy dowódcy eskadry i w obliczu trwającej nieobecności 1LT Igorczyka, na 1LT Kisi otrzymał oficjalne mianowanie. Były XO niezmiennie wspiera zespół technicznie, a wszyscy oczekują jego powrotu z edukacyjnego wygnania. Nowemu życzylibyśmy powodzenia ale szkoda czasu, bo wszyscy widzą, że sobie radzi. Jdnocześnie na zwolnione stanowisko oficera operacyjnego przyjęta została kandydatura 1LT alianta, który z zapałem zabrał się do pracy. Wywołało to zrozumiałą trwogę i poruszenie w kantynie oficerskiej. Wiadomo, nic gorszego, niż nowy z pomysłami.
<br><br>
Sezon urlopowy trwa, stąd i loty i szkolenia odbywają się rzadziej niz zwykle. Niemniej 2LT soczkien zakończył szkolenie ogólnolotnicze i od razu rzucił się, wraz z 2LT Dom''em na szkolenia bojowe. Mimo początkowych sukcesów zachęcamy do wytrwałości i utrzymywania tempa. Droga do końca szkolenia jest zecydowanie dłuższa, niż to się z początku wydaje. A że na początku zdaje się nie mieć końca...', '2021-08-08'),
(30, 'Przygotowania do wypłynięcia', 'Powrót do lotów po wakacjach nie jest łatwy. Brzuchy urosły od grilla i te sprawy. Na szczęście operacyjny dba o to, żeby nikt się nie nudził. Loty z maskowaniem terenem, walka BVR i naloty w ugrupowaniu urozmaicają standardowy cykl szkoleniowy. Październik-listopad to zawsze pracowite miesiące, wiec cały ten trening powinien się bardzo przydać.
<br><br>
Z resztą, użyteczność ćwiczeń jest już widoczna. Doświadczenia z lotów planowych pozwoliły 1LT Bonqu zidentyfikować potrzebę szkoleniową eskadry i tym samym na ukończeniu jest już pierwsza wewnętrzna publikacja autorstwa pilota z tzw. ''drugiego pokolenia'', która obejmie zakresem techniki uderzenia sekcją przeciwko bronionym celom naziemnym.
<br><br>
Z innych wydarzeń, kilku wybranych członków eskadry szykuje się też do gościnnego występu w ramach wirtualnej defilady z okazji Dnia Niepodległości, gdzie pilotować będą muzealne egzemplarze MiG-19P. Żeby nie było, że my tylko fly-by-wire;)', '2021-09-13'),
(31, 'WInter Is Coming', 'Zwiększająca się częstotliwość lotów i treningów, niczym Mariah Carey w radiu, niechybnie zwiastuje nadchodzący sezon świąteczny. Eskadra intensywnie zapoznaje się z nowymi bugami radaru Horneta oraz zmienioną logiką naprowadzania AIM-120. Skuteczne niegdyś techniki notchowania przestały przynosić rezultaty i tym samym walka kinetyczna pozostaje chwilowo jedynym wyjściem. Ponadto w komplecie ze zmniejszonym zużyciem paliwa i poprawionymi parametrami oporów powietrza, dostaliśmy dla wyrównania zkrowienie lotek, więc i BFM trzeba się uczyć na nowo.
<br><br>
A skoro o tym mowa, to wielkie wyrazy uznania należą się pierwszemu Wombatowi, który przebił się do ĆWIERĆFINAŁÓW  czwartej edycji Gildiańskiego Cupa. 1st Lt Kisi wyszedł z niepokonany z grupy 4, w której starł się z takimi weteranami wirtualnego lotnictwa jak 313_Qba i 203_i_31_Bartek23485713497813098756. <a href="https://youtu.be/aMU6TBNaE7U?t=873" target="_blank">W swojej walce pucharowej</a> prowadził już 2:1 z późniejszym finalistą 6WELT_ProSto i w zaciętej walce uzyskał skuteczne trafienia, po których przeciwnik dymiąc obficie zdawał się chylić ku upadkowi. Niestety, jak to później podsumował XO 6WELT JankeS - braki w modelu lotu Viper nadrabia modelem zniszczeń. Kisi zrelaksowany wyrównał lot, czekając na ogłoszenie końca rundy, podczas gdy ProSto bez emocji, pewnie wykorzystał jego nieuwagę i zakończył walkę na swoją korzyść. Oddając sytuacji sprawiedliwość, w DCS nie takie rzeczy się zdarzają. Także nauka z tego taka, drogie dzieci, że wroga, który się nie rozpadł, trzeba dla pewności odprowadzić do samej ziemi. 
<br><br>
Dla porządku składamy gratulacje wszystkim pozostałym uczestnikom, a szczególnie Veronowi, który wygrał turniej już po raz drugi, po rocznej przerwie, zafundowanej mu w poprzedniej edycji przez 333_Baseballa. 
<br><br>
No i na koniec, z okazji prawdziwego święta założenia Korpusu Piechoty Morskiej Stanów Zjednoczonych wirtualni Marines życzą sobie absolutnie wszystkiego najlepszego, ale przede wszystkim więcej czasu na latanie. Odpowiednie wnioski, tłumaczące jak ważne jest zapewnienie odpowiedniej liczby godzin w powietrzu, zostały już wysłane przez dowódcę eskadry do szanownych małżonek członków eskadry oraz do kierowników ich zakładów pracy.
<br><br>
You''re welcome!', '2021-11-10'),
(32, 'Szczęśliwego 2022!', 'Cała ekipa Wombatów życzy wszystkim którzy zabłądzą na tę stronę jak najwięcej spokoju, radości i wszelkiej pomyślności w nowym, 2022 roku!', '2021-12-28'),
(33, 'Cuda noworoczne', 'Na specjalny wniosek Pani Frani z kantyny, Admirał w trybie pilnym zapoznał się z raportem Lt Bonqu z op. Sudden Flash 4 i wystawił pozytywną ocenę ze szkolenia bojowego 2Lt Jettax. Tym samym, po krótkim półtora roku szkolenia, zostaje on wciągnięty na stały skład eskadry i awansowany do pełnego porucznika (z chwilą ogłoszenia). Gratulujemy! Widać marzenia się jednak spełniają. Niemniej nauczony tym wspaniałym doświadczeniem CO postanowił wprowadzić wymóg ciągłości szkoleń od wszystkich kadetów, coby nikt więcej nie musiał zaznawać piekła szkolenia podstawowego przez tak długi czas.
<br><br>
Op. Sudden Flash 4 była pierwszą misją gildia.org w 2022 roku i jako pierwsza w cyklu okazała się do przejścia! Ten nieoczekiwany rezultat zaskoczył wszystkich i zainicjował plotki, jakoby CO tracił swój talent do rozpieprzania całych packegów przez bezmyślne ustawianie przeważających sił przechwytujących po stronie czerwonych. Na szczęście źródła bliskie mission makerom potwierdziły, że w przypływie noworocznego miłosierdzia, dwa flighty opforu zostały usunięte niecałe pół godziny przed misją. W związku z tym spadły tylko wszystkie Harriery, zestrzelone przez jednego z Su-27, który z laserową precyzją olał pozostałych uczestników ruchu lotniczego i strącił je trzema pociskami IR. Dwa kolejne poleciały do Hornetów 2Lt Poko i pilota Navy Mavericka z 203rd Flying Dolphins (czy jakoś tak). Na szczęście Hornet ma silniki, więc udało im się uciec. Znaczy sorry, pokonać pociski kinetycznie. Myślę, że dzielny pilot Suchoja, <a href="https://youtu.be/lmfdbtzIWqw?t=3421" target="_blank">strącony potem w walce kołowej przez Barusa w F-14B</a>, zasłużył co najmniej na F.
<br><br>
Tak więc w nowy rok Wombaty wchodzą w dobrym stylu i oby to była wróżba na pozostałych 12 miesięcy.
<br><br>
<iframe width="560" height="315" src="https://www.youtube.com/embed/ehWmp8jT9N4?controls=0" title="YouTube video player" frameborder="100" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen>; style="margin-left: 100px"></iframe>', '2022-01-07'),
(34, 'Q1 2022 report', 'Ponieważ szef i jedyny członek sekcji prasowej eskadry przeżywa zawodowe rewolucje, newsfeed delikatnie stracił na aktywności. A wydarzyło się sporo, bo choćby po półora roku działaności, 18.01.2022, eskadra zaliczyła swoją setną misję bojwą. A była to misja bardzo udana. Ekipa nabiła w sumie 5 zestrzeleń i odleciała na odświętnego kebaba do Incirlik. Jeden tylko XO nie potrafił odwrócić się od swojego zamiłowania do służby i wrócił na lotniskowiec. Nie jest wiadome, czy mieli tam choćby falafel.
<br><br>
Statystyki wykazały, że tak XO jak i CO wykręcili swoje pierwsze 500 godzin w powietrzu, jako członkowie eskadry. W tym XO niestety prowadzi, na szczęście jeszcze nie w zestrzeleniach:P.
<br><br>
W maju, 2LT Dom ukończył cykl szkoleniowy jako jedny z trzech kadetów ostatniego naboru. Będzie lecieć misję zaliczeniową na nadchodzącym <a href="https://forum.gildia.org/gildia/event?mid=1898" target="_blank"> Op Sudden Flash 4, 31.05.2022</a>. Z misji na misję w kampanii Sudden Flash przeżywa coraz więcej pilotów, więc trzymamy kciuki, by trend się utrzymał. Oznacza to też, że czas rozpocząć oficjalny nabór kandydatów na kadetów. Ciekawe, kogo poznamy w tym roku.
<br><br>
No i w końcu z okazji,  ponieważ Top Gun:Maverick w stylu przypominającym produkty ED w końcu wychodzi z bety, odbędzie się <b>pierwszy zlot eskadrowy</b>. Miejsce spotkania: Łódź 04-05.06.2022 (bo XO musi jakiś maraton czy co tam, akurat na premierę).
<br><br>
"Łodzian" zapraszamy do spotkania.', '2022-05-13');